### ISSUE TITLE
Typos in OIR-Server/Controller/AuthController.js File

### ISSUE THREAD

**Issue by Rohit-Nandagawali** [OIR-WEB-DEV/OIR-Server#5]
### I have found several typos in the AuthController.js file located in the OIR-Server/Controller directory. The typos are listed below with the correct spellings:

- Line 48: "requied" should be "required"
- Line 59: "invalide" should be "invalid"
- Line 83: "invalide" should be "invalid"
- Line 87: "invalide" should be "invalid"
- Line 119: "successfullt" should be "successfully"

I suggest that these typos be corrected to improve the readability and professionalism of the code.

**Comment by Akash-Tandale001** [comment]
Thank you @Rohit-Nandagawali
